<?php
/**
 * Created by PhpStorm.
 * User: darksy
 * Date: 15/12/2015
 * Time: 11:49
 */

namespace MovieUser\Controller;


use Zend\Mvc\Controller\AbstractActionController;

class RegistrationController extends AbstractActionController
{
    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }
}